#- mysql:5.7
#- redis:3.2
#- web from Dockerfile of web (build is required)
version: '3.2'

services:
  api:
    build: api
    volumes:
      - "./api:/asdfasdf"
    command: go run app.go
    ports:
    - "8080:8080"
